
cont = 0
lucro = 0
lucro_porcentagem = 0.0
lucro_total = 0
arr_ma14_bnbETH = []   
arr_ma36_bnbETH = []
arr_ma14_solBNB = []
arr_ma36_solBNB = []
arr_ma14_solETH = []
arr_ma36_solETH = []
arr_ma14_adaBNB = []
arr_ma36_adaBNB = []
arr_ma14_adaETH = []
arr_ma36_adaETH = []
minhas_moedas = []
valor_compra = 0.0
comprado = 0
bnbETH = 'BNBETH'
solBNB = 'SOLBNB'
solETH = 'SOLETH'
adaBNB = 'ADABNB'
adaETH = 'ADAETH'
lista_moedas = ['BNBETH', 'SOLBNB','SOLETH', 'ADABNB', 'ADAETH']
pares_sol = [lista_moedas[1], lista_moedas[2]]
pares_ada = [lista_moedas[3], lista_moedas[4]]
pares_bnb = [lista_moedas[1], lista_moedas[3]]
pares_eth = [lista_moedas[0], lista_moedas[2], lista_moedas[3]]
cotacao_outro_par = 0